### ISSUE TITLE
Montly report

### ISSUE THREAD

**Issue by ronanbrowne** [sorekz/user-activity-report#11]
Is it possible to configure the report to be monthly, i know i can do the last 30 days.

But i want to generate a report for each month if possible.

**Comment by sorekz** [comment]
I think that can be done with a small adjustment to the action.
I'd add a `since` and `until` field that can be used instead of the `since-days` to filter a range and take an ISO-8601 string as input. Does that work for you?
```
- uses: sorekz/user-activity-report@v1
  with:
    token: ${{ secrets.TOKEN }}
    organization: 'your-org'
    since: 2023-01-01 # =2023-01-01T00:00:00.000Z
    until: 2023-02-01 # =2023-02-01T00:00:00.000Z, alternatively use 2023-01-31T23:59:59.999Z if you want to be exact
```

If you want you can contribute the change, if not I'll probably find time to implement that at the weekend myself.

**Comment by ronanbrowne** [comment]
Appreciate the feedback, That works for me, I'm not much of a typeScript guy so i'll leave it to the pros :)

**Comment by sorekz** [comment]
Implemented with #12
I decided that the `until` value is exclusive. That should be more straight forward.

To get a report for the previous month you can execute this workflow (since: 1st of (current month-1 month), until: 1st of current month). The JavaScript Date automatically considers boundaries, so this also works when executed in January.
Added more examples in the README.
```yaml
name: 'User Activity Report'
on:
  workflow_dispatch:
  
jobs:
  'create-report':
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: since-date
        with:
          script: return new Date(new Date().getFullYear(), new Date().getMonth() - 1, 1) 
          result-encoding: string
      - uses: actions/github-script@v6
        id: until-date
        with:
          script: return new Date(new Date().getFullYear(), new Date().getMonth(), 1) 
          result-encoding: string
      - uses: sorekz/user-activity-report@v1
        with:
          token: ${{ secrets.TOKEN }}
          organization: 'your-org'
          since: ${{ steps.since-date.outputs.result }}
          until: ${{ steps.until-date.outputs.result }}
```
